### ISSUE TITLE
succeeded but returns error anyway

### ISSUE THREAD

**Issue by MarvinNazari** [rheinfabrik/Heimdall.swift#58]
Hi, i send a request to my server and i get the access_token back, but in the requestAccessToken block i get .Failure result, here is my code

    let credentials = OAuthClientCredentials(id: "ede4499a639710a0b5107b7b00df3cece194114871f2add64f3cd93a9418a197", secret: "4045de00ec7505f0f8e980aa063311dc8118f1bfdb7e5d160fa35eea60ee6ab5")
    
    
    let tokenURL = NSURL(string: "http://localhost:3000/oauth/token")!
    let heimdall = Heimdall(tokenURL: tokenURL, credentials: credentials)
    
    heimdall.requestAccessToken(username: username, password: password) { result in
        switch result {
        case .Success:
            println("success")
        case .Failure(let error):
            println("failure: \(error)")
        }
    }

and i get back this

    failure: Error Domain=HeimdallErrorDomain Code=1 "Could not authorize grant" UserInfo=0x7fb86481cd40 {NSLocalizedDescription=Could not authorize grant, NSLocalizedFailureReason=Expected access token, got: {"access_token":"a0752d03bd4ac7200f0cd739f1a411df1885d47f24a3ab1c6b216c435a199847","token_type":"bearer","scope":"public","created_at":1434027186}.}

thanks in advance

**Comment by MarvinNazari** [comment]
i find the problem, in my response i don't get back `expires_in`, shouldn't that be optional?

**Comment by felixjendrusch** [comment]
Indeed, `expires_in` is only [`RECOMMENDED`](https://tools.ietf.org/html/rfc6749#section-4.2.2). I think we are treating it as optional but I will double check, thanks!
